language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: aYxs8hlTbpYYwmkgjyPa6bJBSwcpdUreT4y20N/EADxegPYDB4ueGvfOS2m8noCeeiTYobUUejE360FnyHoshbrnva0Xsc4FIjJiQ/04P0bnBfUDdYx2oLngDHdgDDtEmJyPm3rTZnzYnr2LeNTx/IPkv7jQOCzdndV/2Vj1A7orv6C04ss6grTS/Mjya4m3xZ7CcNuMfBu7LN0+X76Ewop7OpfL0bbotAUdYk/R8GJ675IvtiKCwWarTDdOajCUTBmrNMd7z/3qr8mNaatT8zPKLv8rOm+fm45BWy6WavRZFtiUdLFvJZmCRg/PteOR4Ve1z4cZT8b1/BQzGjeLgvAxZr/biB97h4SEMWoLkBbDIqE2QZNrDeiIJPl9hxlCEwinDs032kjMG/FfB4mZx4OtV+9mRNM6EdgjjyPg0Xz7BdNa2vy1qpV/oD9oCAxqOpv3zYbr6pXApWAs4zvL9PKHshjOqGbE2soNiqVuxGGN0D+o2Mrb+Ea4Whb36TKDv5njk0VPU2t0bsbYg/KItc8vnPYGu0hgEZ+r7U/zXqSp6WKOhCzPbMEYpqT6WTYkokqAFNrVvQJl6+/VIWIMnqoSitYQLKD5OOe7QQJ1Q6IMK5DIlQjtvV2xOLNL78wqIRRMzGkiQ9aC4ESmDMPOZZGeOIVXQnxJBYriMpheqwY=
  app: immense-ridge-55909
  on:
    repo: annahisenberg/food-diary-node
